# Site settings
title: Ika Eriksson Web
email: ulliskristina@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A website presenting the web developing work of Ulrika Eriksson. Please feel free to contact
  her for inquiries.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username:
github_username:  UlrikaEriksson

# Build settings
markdown: kramdown
